### ISSUE TITLE
regular house cleaning

### ISSUE THREAD

**Issue by ikke-t** [RedHat-EMEA-SSA-Team/hetzner-ocp4#99]
I'd appreciate if there was some regular pruning of images and builds set to automation. The second time I run out of disk space on host, after the automatic upgrade. I believe it collects so much container images, and deletes nothing of the old. So this kills the VMs on my machine, and leads to re-install.

Perhaps a kube cron-job to do pruning for both images and builds. And that is not just registry images, but cached images on hosts.

**Comment by rbo** [comment]
Do you have a good suggestion? How do we best implement this?

**Comment by ikke-t** [comment]
I'd need to check, but I recall recent version came out with such an option. I recall seeing it on roadmap.

**Comment by ikke-t** [comment]
https://docs.openshift.com/container-platform/4.5/applications/pruning-objects.html#pruning-images_pruning-objects

That's the way to set it automatically to prune images. That job should be pushed to fresh OCP cluster.

**Comment by rbo** [comment]
> https://docs.openshift.com/container-platform/4.5/applications/pruning-objects.html#pruning-images_pruning-objects

If I understand it correctly this is only for image registry node for images on node level.

With the new add-ons support, you can write your own role to run some post-install steps if you like: [docs/add-ons.md](https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/master/docs/add-ons.md)

I would like to close the Issue because I destroy and recreate my cluster to often to find out the proper configuration. Please reopen this issue with the proper configuration or direct a PR or an add-on... 

If you have any further questions, please let me know or open again.
